# Generated by Django 4.0.4 on 2022-05-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedorder',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MB', 'Mobile'), ('LT', 'Laptop'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear'), ('MW', 'Mens Wear'), ('WW', 'Womens Wear'), ('KW', 'Kids Wear'), ('FT', 'Footwear'), ('FR', 'Furniture'), ('GR', 'Grocery'), ('ET', 'Electronics'), ('GM', 'Grooming'), ('TY', 'Toy'), ('FC', 'Fashion')], max_length=10),
        ),
    ]
