# Generated by Django 4.0.4 on 2022-09-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('smartphone', 'Smartphone'), ('laptop', 'Laptop'), ('top Wear', 'Top Wear'), ('bottom Wear', 'Bottom Wear'), ('mens wear', 'Mens Wear'), ('womens wear', 'Womens Wear'), ('kids wear', 'Kids Wear'), ('shoes', 'Shoes'), ('furniture', 'Furniture'), ('grocery', 'Grocery'), ('electronics', 'Electronics'), ('grooming', 'Grooming'), ('toy', 'Toy'), ('fashion', 'Fashion')], max_length=50),
        ),
    ]
